# Generated by Django 2.0.9 on 2018-11-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20181129_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asensor',
            new_name='Ascensor',
        ),
    ]
