# Generated by Django 2.0.9 on 2018-11-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20181129_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ascensor',
            old_name='pertenece',
            new_name='id_cliente',
        ),
    ]
