INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (1, 'Can add permission', 1, 'add_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (2, 'Can change permission', 1, 'change_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (3, 'Can delete permission', 1, 'delete_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (4, 'Can add group', 2, 'add_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (5, 'Can change group', 2, 'change_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (6, 'Can delete group', 2, 'delete_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (7, 'Can add content type', 3, 'add_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (8, 'Can change content type', 3, 'change_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (9, 'Can delete content type', 3, 'delete_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (10, 'Can add user', 4, 'add_customuser');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (11, 'Can change user', 4, 'change_customuser');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (12, 'Can delete user', 4, 'delete_customuser');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (13, 'Can add log entry', 5, 'add_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (14, 'Can change log entry', 5, 'change_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (15, 'Can delete log entry', 5, 'delete_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (16, 'Can add session', 6, 'add_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (17, 'Can change session', 6, 'change_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (18, 'Can delete session', 6, 'delete_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (19, 'Can add cliente', 7, 'add_cliente');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (20, 'Can change cliente', 7, 'change_cliente');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (21, 'Can delete cliente', 7, 'delete_cliente');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (22, 'Can add asensor', 8, 'add_asensor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (23, 'Can change asensor', 8, 'change_asensor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (24, 'Can delete asensor', 8, 'delete_asensor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (25, 'Can add ascensor', 8, 'add_ascensor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (26, 'Can change ascensor', 8, 'change_ascensor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (27, 'Can delete ascensor', 8, 'delete_ascensor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (28, 'Can add cliente_ tecnico', 9, 'add_cliente_tecnico');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (29, 'Can change cliente_ tecnico', 9, 'change_cliente_tecnico');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (30, 'Can delete cliente_ tecnico', 9, 'delete_cliente_tecnico');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (31, 'Can add cliente_ tecnico', 10, 'add_cliente_tecnico');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (32, 'Can change cliente_ tecnico', 10, 'change_cliente_tecnico');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (33, 'Can delete cliente_ tecnico', 10, 'delete_cliente_tecnico');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (34, 'Can add association', 11, 'add_association');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (35, 'Can change association', 11, 'change_association');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (36, 'Can delete association', 11, 'delete_association');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (37, 'Can add code', 12, 'add_code');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (38, 'Can change code', 12, 'change_code');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (39, 'Can delete code', 12, 'delete_code');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (40, 'Can add nonce', 13, 'add_nonce');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (41, 'Can change nonce', 13, 'change_nonce');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (42, 'Can delete nonce', 13, 'delete_nonce');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (43, 'Can add user social auth', 14, 'add_usersocialauth');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (44, 'Can change user social auth', 14, 'change_usersocialauth');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (45, 'Can delete user social auth', 14, 'delete_usersocialauth');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (46, 'Can add partial', 15, 'add_partial');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (47, 'Can change partial', 15, 'change_partial');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (48, 'Can delete partial', 15, 'delete_partial');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (49, 'Can add application', 16, 'add_application');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (50, 'Can change application', 16, 'change_application');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (51, 'Can delete application', 16, 'delete_application');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (52, 'Can add access token', 17, 'add_accesstoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (53, 'Can change access token', 17, 'change_accesstoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (54, 'Can delete access token', 17, 'delete_accesstoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (55, 'Can add grant', 18, 'add_grant');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (56, 'Can change grant', 18, 'change_grant');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (57, 'Can delete grant', 18, 'delete_grant');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (58, 'Can add refresh token', 19, 'add_refreshtoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (59, 'Can change refresh token', 19, 'change_refreshtoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (60, 'Can delete refresh token', 19, 'delete_refreshtoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (61, 'Can add site', 20, 'add_site');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (62, 'Can change site', 20, 'change_site');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (63, 'Can delete site', 20, 'delete_site');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (64, 'Can add email address', 21, 'add_emailaddress');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (65, 'Can change email address', 21, 'change_emailaddress');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (66, 'Can delete email address', 21, 'delete_emailaddress');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (67, 'Can add email confirmation', 22, 'add_emailconfirmation');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (68, 'Can change email confirmation', 22, 'change_emailconfirmation');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (69, 'Can delete email confirmation', 22, 'delete_emailconfirmation');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (70, 'Can add social account', 23, 'add_socialaccount');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (71, 'Can change social account', 23, 'change_socialaccount');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (72, 'Can delete social account', 23, 'delete_socialaccount');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (73, 'Can add social application', 24, 'add_socialapp');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (74, 'Can change social application', 24, 'change_socialapp');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (75, 'Can delete social application', 24, 'delete_socialapp');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (76, 'Can add social application token', 25, 'add_socialtoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (77, 'Can change social application token', 25, 'change_socialtoken');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (78, 'Can delete social application token', 25, 'delete_socialtoken');
