# Generated by Django 2.0.9 on 2018-12-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='fallas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='hora_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='piezas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
