# Generated by Django 2.0.9 on 2018-12-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_auto_20181130_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente_tecnico',
            old_name='id_usuario',
            new_name='id_tecnico',
        ),
    ]
