# Generated by Django 2.0.9 on 2018-12-01 02:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0005_auto_20181130_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 2, 23, 25, 953080, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='id_tecnico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
