# Generated by Django 2.0.9 on 2018-12-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0006_auto_20181130_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_tecnico',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Terminada')], default='1', max_length=50),
        ),
    ]
