# Generated by Django 2.0.9 on 2018-12-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0007_cliente_tecnico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_tecnico',
            name='hora_termino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
