# Generated by Django 2.0.9 on 2018-11-24 13:36

from django.db import migrations
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', usuario.models.UserManager()),
            ],
        ),
    ]
